### PR TITLE
cmake - implement out of source tree building, some minor cleanups

### PR DESCRIPTION
**Pull request by saknopper**
So now you can do

```
cd gmic
mkdir build
cd build
cmake ..
make
```
Even the man page and bash completion file are created inside the `build` directory.

Note: I have pretty much reverted the previous merge request ( dtschump/gmic#41 ). I think it's better this way, but maybe I'm overlooking something. Let me know if I have.

### CODE REVIEW

**Comment by dtschump** [comment]
Thanks Sander. This needs to be discussed.
To be honest, It would be really more simple for @c-koi (developer of the QT-version of the plug-in) and myself to assume the generated binaries always come in 'gmic_root_folder/src/' (and probably same applies for the man page, in 'gmic_root_folder/man'). The idea is that we already have a `Makefile` and `.pro` files that assume this is the case, and it should be coherent to keep the same location regardless of the build system used.
What do you think about it ?

**Comment by saknopper** [comment]
I already thought so! :)

Anyway, my primary concern here is the cmake-based build system. Obviously you're free to use the regular `Makefile` and `.pro` files to keep the old behaviour. I understand you're now also using the cmake build system to test things, but normally you would just stick to a single build system and not mix them.

My long-term goal (for the cmake build) is to compile a shared library by default and install the library and `gmic.h` header system-wide. This way I'm hoping gmic-qt can simply check for the presence of the library and header file in its `CMakeLists.txt` and use those. But again, my goal is only for the cmake-based build to work this way.

In my opinion this is a clean solution, treating gmic as a library (of course with the cli binary) and gmic-qt as a separate project which uses the gmic library.

This in an effort to make it easier for downstream packagers to package this software.

**Comment by dtschump** [comment]
This makes sense :)
I've two concerns anyway:

1. I understand that having a dynamic library used by many G'MIC interface could be somehow desirable for someone who wants all G'MIC interfaces installed on his system. **But**, this is not the case for someone who wants only the plug-in for instance. Dependencies for the whole stuff is way too large for the plug-in user (particularly having OpenCV installed would be a disaster, for the plug-in-only user). That's why the default behavior should always be to disable dynamic linking.

2. As I said on pixls.us, the current version of the `CMakeLists.txt` does not enable the optimisation flags by default. This is a big concern, as a lambda user cloning the git repository, and seeing a `CMakeLists.txt` could be tempted to use it and get a non-optimized version of G'MIC, with all the negative feelings that come along. Could that be fixed ? 

Thanks !

**Comment by saknopper** [comment]
1. I'm fine with disabling dynamic linking by default, no problem.
2. Should be fixed in the commits I've just added

One other question though: how do you feel about disabling the build of the (old) gtk gimp plugin by default? I'm not sure, but I'm guessing you want people to use gmic-qt or not?

**Comment by dtschump** [comment]
Thanks. We have discussed with @c-koi and we have something to propose that could please everyone.
The idea is to have two different cases:
- If `cmake` is run from the `gmic/` root directory (that contains then `src/` and `man/`), then the generated binaries would be output in `src/` and the man page in `man/`.
- If `cmake` is run from a `build/` directory, then the generated binaries and man page would be output in `build` instead (just as you propose).
Apparently this is a simple test to add, ad there are pre-defined variables in `cmake` that point to the locations of the build directory, and the directory that contains the `CMakeLists.txt` file. If there are the same, we are in the first case, otherwise, in the second case.
What do you think about it ?

**Comment by dtschump** [comment]
> One other question though: how do you feel about disabling the build of the (old) gtk gimp plugin by default? I'm not sure, but I'm guessing you want people to use gmic-qt or not?

Yes, G'MIC-Qt should be the preferred way of using the plug-in, so disabling the GTK version by default seems to be a good idea !

**Comment by saknopper** [comment]
Your idea about the 2 different cases sounds good to me, I can definitely do that! Do you want me to do that before merging this or can I work on it this weekend or somewhere next week?

I can disable the GTK-based plugin, that's a quick one to do.

**Comment by saknopper** [comment]
I cleaned things up a bit more as well, besides disabling the GTK-based plugin.

Is it ok to merge this? Especially due to the optimization flags it might be worth it.

Either way, I will work on the 2 cases you've described earlier later this weekend or otherwise next week at the latest.

**Comment by dtschump** [comment]
OK, thanks for all your efforts. I'll merge this one.
The 2-case trick will be really useful for us, from a developer perspective :)
Maybe the best way of selecting the case would be just to check if a 'src/' subfolder is present in the current build directory, and if so, make it the location of the generated binaries (otherwise keep the build folder). Same for the man pages.
Thanks a lot !!

**Pull request merged**
