### PR TITLE
Add travis support

### PR DESCRIPTION
**Pull request by devernay**
- fix zart.pro for portability (it even works with -spec macx-xcode on osx)
- zart: compile our own gmic.o instead of using libgmic which adds more dependencies
- zart: include gmic.h before CImg.h

### CODE REVIEW

**Comment by dtschump** [comment]
Looks like there's a problem with the build on Travis : 

https://travis-ci.org/dtschump/gmic-minimal

(if you can see it..).

**Comment by devernay** [comment]
yes, and I can even scroll down the log and read:

RCC: Error in 'zart.qrc': Cannot find file 'images/splash.png'

did you remove that file?

**Comment by devernay** [comment]
here's the build for the branch I used for the pull request:
https://travis-ci.org/devernay/gmic/builds/82528860 <https://travis-ci.org/devernay/gmic/builds/82528860>

Once you've set up https://travis-ci.org/dtschump/gmic <https://travis-ci.org/dtschump/gmic> , you will also get automatic builds for all pull requests, and know if the pull request breaks the build

**Comment by dtschump** [comment]
Ah, it seems the splash image was not in the "gmic-minimal" repo (but was in the "gmic" repo, hence my incomprehension). Nice contrib by the way, thanks a lot :)

**Pull request merged**
