### PR TITLE
cmake: Fix build with Xshm

### PR DESCRIPTION
**Pull request by jtojnar**

### CODE REVIEW

**Comment by dtschump** [comment]
Would it be possible next time to have a PR against the 'develop' branch instead ? That would be really nice. Thanks!

**Comment by jtojnar** [comment]
Will try to remember that (by default https://github.com/cli/cli sends a PR agains the default branch).

**Comment by dtschump** [comment]
By the way, I've ported your patch to the `develop` branch anyway :).
Thanks again !

**Comment by jtojnar** [comment]
Is there some kind of contributing documentation (e.g. https://en.wikipedia.org/wiki/Contributing_guidelines)? I do not see any mention of the develop branch anywhere. What is its purpose and what is purpose of master then? Also why are all the commit messages "."? It makes it really hard to find what commit might have caused a regression.

**Comment by dtschump** [comment]
No, a lot of documentation are actually missing in G'MIC.
Concerning the '.' commit messages: it happens I add commit messages, but sometimes, there is a script that does the commit automatically, and in that case, it just put '.' as a comment.
Not a good practice I know, but this script is also a time saver for other stuffs, so I keep it.

**Pull request merged**
