### PR TITLE
Add support for the cmake build system again

### PR DESCRIPTION
**Pull request by saknopper**
As discussed on the pixls.us discussion board: https://discuss.pixls.us/t/gmic-extremely-slow-to-compile-fix-available/5984/10?u=saknopper

Based on the work of @stefantalpalaru

### CODE REVIEW

**Comment by dtschump** [comment]
Thanks.
I'm getting a strange error when trying to build with the provided `CMakeLists.txt`. Do you have any idea why this does not work ?
My way of doing : 
~~~~
$ cd gmic
$ mkdir build && cd build
$ cmake ../resources/CMakeLists.txt 
X11_INCLUDE_DIR: /usr/include
X11_INCLUDE_DIRs: 
X11_LIBRARY_DIR: /usr/lib/x86_64-linux-gnu
X11_LIBRARY_DIRS: 
-- Checking for module 'fftw3>=3.0'
--   Found fftw3, version 3.3.6-pl2
-- Checking for module 'opencv'
--   Found opencv, version 3.1.0
-- Checking for module 'GraphicsMagick++'
--   No package 'GraphicsMagick++' found
-- Checking for module 'OpenEXR'
--   Found OpenEXR, version 2.2.0
-- Configuring done
CMake Error at CMakeLists.txt:225 (add_library):
  Cannot find source file:

    ./src/gmic.h

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error: CMake can not determine linker language for target: libgmic
CMake Error: Cannot determine link language for target "libgmic".
CMake Error: Cannot determine link language for target "libgmicstatic".
CMake Error: CMake can not determine linker language for target: libgmicstatic
CMake Error: CMake can not determine linker language for target: gmic_gimp_gtk
CMake Error: Cannot determine link language for target "gmic_gimp_gtk".
CMake Error: CMake can not determine linker language for target: gmic
CMake Error: Cannot determine link language for target "gmic".
-- Generating done
-- Build files have been written to: /home/dtschump/work/src/gmic/resources
~~~~
I've tried different things, different locations for the build folder and the `CMakeLists.txt` file, but I always get this same error. I'm running cmake 3.9.1 on Ubuntu 17.10.

**Comment by saknopper** [comment]
You can build it by doing:

```
cd gmic
cp resources/CMakeLists.txt .
cmake .
make
```
I could also place the `CMakeLists.txt` file in the root directory of the project, that way you wouldn't need to copy it first. But as far as I'm aware `CMakeLists.txt` has always resided in the `resources` directory, right?

**Comment by dtschump** [comment]
OK thanks, this was much simple than I thought :)
> I could also place the CMakeLists.txt file in the root directory of the project, that way you wouldn't need to copy it first. But as far as I'm aware CMakeLists.txt has always resided in the resources directory, right?
I don't remember exactly where it was, but if we have now a nice working `CMakeLists.txt` that is supposed to be run from the root directory, then we should probably put it there for the sake of simplicity :)

**Comment by dtschump** [comment]
Or could it be better if the cmake process should be run from a temporary `build/` subfolder ?
I'm not familiar enough with `cmake`, so I trust you about the usual way of doing it.

**Comment by dtschump** [comment]
It seems to work fine. I've noticed that the produced binary files are larger than those generated with the 'regular' Makefile. In fact they are not 'stripped'. Do you think this is an option that could be added to the `CMakeLists.txt` ?
For instance, the size of the `gmic` binary (cli interface) is 8Mb versus 6.3Mb for the one generated with my Makefile.
That looks good anyway.

**Comment by saknopper** [comment]
Good to hear that it works now!

I'm not a cmake wizard, but as far as I understand `CMakeLists.txt` should be in the root of the project and can't be in de build subfolder because the sources a referred to relative to `CMakeLists.txt`. Building in a separate `build` subfolder would indeed be nicer and is definitely something I will look into. But the way it is now is also the way it was before, when `CMakeLists.txt` was still around. So nothing has changed in that regard as far as I'm aware.

The binaries could indeed be bigger because they're not stripped. This is intentional because the exact compile flags to be used with regard to optimizations are usually chosen/overridden by distributions/packagers. They can easily be set by using environment variables. The same applies to stripping the binaries.

**Comment by saknopper** [comment]
Actually, the location of `CMakeLists.txt` has changed between releases. For example, version 2.0.0 has it in the project root folder, while version 2.1.0 has it in the `resources` subfolder.

I would prefer to have it in the project root folder, if you have no strong feelings about it.

**Comment by dtschump** [comment]
OK, so everything is fine.  I'll merge the pull request, and move the file to the root directory then.
Thanks again!

**Comment by dtschump** [comment]
Done. Maybe you should add your name and a license as comments in the `CMakeLists.txt` ?
I've also added you as a contributor on the G'MIC web page. Maybe you have a website you want me to link to ?

**Comment by saknopper** [comment]
I will copy the header from your Makefile and adjust it.

Thanks for adding me as a contributor! That wasn't really necessary for this small contribution... Anyway, it would be great if you could link to my website: http://sanderknopper.nl

**Comment by jtojnar** [comment]
Is there a tarball that includes both CMakeLists.txt and the headers downloaded by it (`CImg.h`, `gmic_stdlib.h`, `gmic_stdlib.h`, `gmic_gimp_gtk.h`)?

**Comment by dtschump** [comment]
I thought the CMakeLists.txt was in the source .tar.gz available on the website, but it seems it's not the case. That's a bug unfortunately, I have to check my release script to see what happened.

**Pull request merged**
